# 00 PyTorch Fundamentals

In [1]:
print("Hello World")

Hello World


In [2]:
# cheking which device is on 
# !nvidia-smi

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cu126


# Creating Tensors  

In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [9]:
vector = torch.tensor([3,4,5])

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([3])

In [14]:
random_tensor = torch.rand(3,3)

In [15]:
random_tensor.shape

torch.Size([3, 3])

In [16]:
random_tensor.ndim

2

In [17]:
random_tensor_2 = torch.rand(1, 5, 5)
random_tensor_2

tensor([[[0.2733, 0.9031, 0.4298, 0.8241, 0.4010],
         [0.4271, 0.6702, 0.2799, 0.7617, 0.0847],
         [0.4324, 0.6885, 0.7302, 0.8336, 0.9850],
         [0.3539, 0.0282, 0.4308, 0.1716, 0.0253],
         [0.3084, 0.9045, 0.2435, 0.3628, 0.2907]]])

In [18]:
random_tensor_2.shape

torch.Size([1, 5, 5])

In [19]:
random_tensor_2.ndim

3

In [20]:
# Random image tensor
random_img_tensor = torch.rand(size = (224, 224, 3))
random_img_tensor

tensor([[[0.2773, 0.9958, 0.2774],
         [0.6302, 0.5986, 0.6715],
         [0.2573, 0.8313, 0.4947],
         ...,
         [0.1625, 0.8423, 0.3887],
         [0.4285, 0.1485, 0.0373],
         [0.3309, 0.5027, 0.3531]],

        [[0.6696, 0.5561, 0.4740],
         [0.9968, 0.4464, 0.8504],
         [0.0684, 0.4132, 0.9668],
         ...,
         [0.5972, 0.4685, 0.2651],
         [0.8185, 0.5610, 0.7235],
         [0.2757, 0.8322, 0.4028]],

        [[0.4474, 0.6294, 0.8000],
         [0.9916, 0.2024, 0.3640],
         [0.5194, 0.7538, 0.7935],
         ...,
         [0.1775, 0.0668, 0.3686],
         [0.8459, 0.9378, 0.2334],
         [0.3374, 0.3576, 0.3173]],

        ...,

        [[0.9352, 0.3361, 0.1049],
         [0.2680, 0.7133, 0.8492],
         [0.3692, 0.0298, 0.7151],
         ...,
         [0.3245, 0.7319, 0.5626],
         [0.0255, 0.5112, 0.2443],
         [0.1997, 0.7451, 0.9199]],

        [[0.7441, 0.6091, 0.7398],
         [0.5880, 0.8481, 0.7859],
         [0.

In [21]:
random_img_tensor.shape, random_img_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# ZEROS AND ONES TENSORS

In [22]:
# zeros tensor
zeros_tensor = torch.zeros(size=(3,3))
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [23]:

# ones tensor
ones_tensor = torch.ones(size=(3,3))
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

# Range Tensor (from one number to another number with a gap)

In [24]:
# arange
one_to_twenty = torch.arange(start=1, end=21, step=1)
one_to_twenty

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20])

# Tensor DataTypes

In [25]:
# float32
tensor_float32 = torch.tensor([1.0, 2.0, 3.0],
                              dtype=torch.float32,
                              device=None,
                              requires_grad=False)

In [26]:
tensor_float32

tensor([1., 2., 3.])

In [27]:
tensor_float32.dtype

torch.float32

In [28]:
# converting tensor_float32 into tensor_float16
tensor_float16 = tensor_float32.type(torch.float16)
tensor_float16

tensor([1., 2., 3.], dtype=torch.float16)

In [29]:
# what happen if we multiply different type of tensor
tensor_float32 * tensor_float16

tensor([1., 4., 9.])

In [30]:
import torch

# Getting information from tensor
* Datatype - tensor.dtype
* shape - tensor.shape
* device - tensor.device

In [31]:
# create random tensor
random_tensor = torch.rand(5,5)
print(random_tensor)

tensor([[0.8895, 0.7883, 0.0917, 0.9268, 0.7454],
        [0.3547, 0.2115, 0.6918, 0.2597, 0.9912],
        [0.9487, 0.2267, 0.1596, 0.8698, 0.9371],
        [0.8106, 0.9795, 0.9195, 0.5893, 0.3745],
        [0.6316, 0.7421, 0.6415, 0.3712, 0.0879]])


In [32]:
print(f"Datatype of random_tensor: {random_tensor.dtype}")
print(f"Shape of a random_tensor: {random_tensor.shape}")
print(f"random_tensor is on device: {random_tensor.device}")

Datatype of random_tensor: torch.float32
Shape of a random_tensor: torch.Size([5, 5])
random_tensor is on device: cpu


# Tensor operation
1. Addition
2. subtraction
3. Multiplication(Element wise)
4. Division
5. Matrix Multiplication

In [33]:
tensor = torch.tensor([5, 10, 15])
print(tensor)

tensor([ 5, 10, 15])


In [34]:
# addition
print(tensor + 10)
print(torch.add(tensor, 10))

tensor([15, 20, 25])
tensor([15, 20, 25])


In [35]:
# subtraction
print(tensor - 10)
print(torch.sub(tensor, 10))

tensor([-5,  0,  5])
tensor([-5,  0,  5])


In [36]:
# multiplication element-wise
print(f"{tensor} '*' {tensor}")
print(tensor * tensor)
print(torch.mul(tensor, tensor))

tensor([ 5, 10, 15]) '*' tensor([ 5, 10, 15])
tensor([ 25, 100, 225])
tensor([ 25, 100, 225])


In [37]:
# Division
print(tensor/5)
print(torch.div(tensor, 5))

tensor([1., 2., 3.])
tensor([1., 2., 3.])


# Matrix Multiplication

In [42]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 508 µs, sys: 0 ns, total: 508 µs
Wall time: 418 µs


tensor(350)

In [54]:
# By using loop
# %%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)


tensor(350)


# Two Main Rules while performing matrix multiplication needs to be well notified: 
1. The inner dimension should match 
* (3,2) @ (3, 3) will won't work 
* (3,3) @ (3,2) will work 

2. The result will be of outer dimension  
* (2,3) @ (3,2) -> (2,2) #@ is also used in place of matmul 

In [56]:
import torch

In [59]:
torch.matmul((torch.rand(2,3)), (torch.rand(3,2)))

tensor([[0.6436, 0.8903],
        [0.5805, 0.9684]])

In [61]:
torch.matmul(torch.rand(2,2), torch.rand(3,2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x2 and 3x2)

In [63]:
# You can use transpose to change the shape of tensor eg:
tensor_A = torch.tensor([[10, 20], 
                         [30, 40], 
                         [50, 60]])

tensor_B = torch.tensor([[5, 10], 
                         [15, 20], 
                         [25, 30]])

print(f"Shape of tensor_A{tensor_A.shape} and Shape of tensor_B {tensor_B.shape}")

Shape of tensor_Atorch.Size([3, 2]) and Shape of tensor_B torch.Size([3, 2])


In [ ]:
# if we try to multiply we will get an error 
tensor.matmul(tensor_A, tensor_B)

TypeError: matmul() takes 1 positional argument but 2 were given

In [73]:
# Use transpose (.T) and again multiply 
tensor_B_T = tensor_B.T
print(f"{tensor_A} @ \n{tensor_B_T}")
print(f"Shape of tensor_A: {tensor_A.shape} Old Shape of tensor_B{tensor_B.shape} \nand Shape after transpose {tensor_B_T.shape}")
print(f"tensor_A: {tensor_A.shape} @ transpose(tensor_B_T) {tensor_B_T.shape}")
print(f"\nOutput")
torch.mm(tensor_A, tensor_B_T)

tensor([[10, 20],
        [30, 40],
        [50, 60]]) @ 
tensor([[ 5, 15, 25],
        [10, 20, 30]])
Shape of tensor_A: torch.Size([3, 2]) Old Shape of tensor_Btorch.Size([3, 2]) 
and Shape after transpose torch.Size([2, 3])
tensor_A: torch.Size([3, 2]) @ transpose(tensor_B_T) torch.Size([2, 3])

Output


tensor([[ 250,  550,  850],
        [ 550, 1250, 1950],
        [ 850, 1950, 3050]])

In [1]:
import torch

## Minimum, Maximum, Mean, Sum (Tensor Aggregation)

In [ ]:
# create tensor from 1 to 199 with gap of 10
x = torch.arange(1,200,10)
print(f"Random Tensor X : {x}")
print(f"Shape of Tensor X: {x.shape}")

Random Tensor X : tensor([  1,  11,  21,  31,  41,  51,  61,  71,  81,  91, 101, 111, 121, 131,
        141, 151, 161, 171, 181, 191])
Shape of Tensor X: torch.Size([20])


In [4]:
# minimum tensor in x 
print(f"Minimum tensor in X : {torch.min(x)}")

Minimum tensor in X : 1


In [6]:
# maximum tensor in x 
print(f"Maximum tensor in X : {torch.max(x)}")

Maximum tensor in X : 191


In [ ]:
# mean tensor in x 
print(f"Mean of tensor X : {torch.mean(x.type(torch.float32))}")

Mean tensor in X : 96.0


In [10]:
# sum tensor in x 
print(f"Sum of tensor X : {torch.sum(x)}")

Sum of tensor X : 1920


In [13]:
# Finding postion of min_value 
x.argmin(), torch.argmin(x)
print(f"Minimum index is {torch.argmin(x)} and value is {x[torch.argmin(x)]}")

Minimum index is 0 and value is 1


In [14]:
# Finding postion of max_value 
x.argmax(), torch.argmax(x)
print(f"Maximum index is {torch.argmax(x)} and value is {x[torch.argmax(x)]}")

Maximum index is 19 and value is 191


## Reshaping, View, Stacking, Squeezing, Unsqueezing, Permute