1. Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). 
See the documentation on torch.Tensor and for torch.cuda.

In [13]:
# 2. Create a random tensor with shape (7, 7).
import torch
random_tensor_A = torch.rand(7,7)
print(random_tensor_A)

tensor([[0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783],
        [0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]])


In [ ]:
# Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the 
# second tensor).
random_tensor_B = torch.rand(1,7).T
print(random_tensor_B)

torch.matmul(random_tensor_A,random_tensor_B)

tensor([[0.5932],
        [0.1123],
        [0.1535],
        [0.2417],
        [0.7262],
        [0.7011],
        [0.2038]])


tensor([[1.1061],
        [0.9868],
        [1.8999],
        [0.7716],
        [1.3174],
        [1.6353],
        [1.7395]])

In [15]:
# 4. Set the random seed to 0 and do exercises 2 & 3 over again.
RANDOM_SEED = 0 

torch.manual_seed(RANDOM_SEED)
random_tensor_x = torch.rand(size=(7,7))

torch.manual_seed(RANDOM_SEED)
random_tensor_y = torch.rand(1,7).T

torch.matmul(random_tensor_x, random_tensor_y )


tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [ ]:
# 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look 
# into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.
# ans: torch.cuda.initial_seed() Return the current random seed of the current GPU.

In [21]:
# 6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) 
# when creating the tensors (this doesn't have to be the GPU random seed).
torch.cuda.is_available()

device = "cuda" if torch.cuda.is_available() else "cpu"

torch.manual_seed(1234)
random_tensor_a = torch.rand(2,3)
random_tensor_a = random_tensor_a.to(device)
print(random_tensor_a, random_tensor_a.device)

torch.manual_seed(1234)
random_tensor_b = torch.rand(2,3)
random_tensor_b = random_tensor_b.to(device)
print(random_tensor_b, random_tensor_b.device)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0') cuda:0
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0') cuda:0


In [25]:
# 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
random_tensor_b_reshaped = random_tensor_b.reshape(3,2)
print(random_tensor_b_reshaped)
matrix_mul = torch.matmul(random_tensor_a, random_tensor_b_reshaped)
print(matrix_mul)

tensor([[0.0290, 0.4019],
        [0.2598, 0.3666],
        [0.0583, 0.7006]], device='cuda:0')
tensor([[0.1204, 0.3411],
        [0.0666, 0.6596]], device='cuda:0')


In [28]:
# 8. Find the maximum and minimum values of the output of 7.
print(f"Maximum: {torch.max(matrix_mul)} and Minimum: {torch.min(matrix_mul)}")

# 9. Find the maximum and minimum index values of the output of 7.
print(f"Maximum Index: {torch.argmax(matrix_mul)} and Minimum Index: {torch.argmin(matrix_mul)}")

Maximum: 0.6596311330795288 and Minimum: 0.06662219762802124
Maximum Index: 3 and Minimum Index: 2


In [36]:
# 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor 
# of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

torch.manual_seed(7)
random_tensor_c = torch.rand(1, 1, 1, 10)
print(random_tensor_c, random_tensor_c.shape)
print()

torch.manual_seed(7)
random_tensor_d = torch.squeeze(random_tensor_c)
print(random_tensor_d, random_tensor_d.shape)

random_tensor_c == random_tensor_d


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])


tensor([[[[True, True, True, True, True, True, True, True, True, True]]]])