# 00 PyTorch Fundamentals

In [ ]:
print("Hello World")

Hello World


In [3]:
# cheking which device is on 
# !nvidia-smi

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


# Creating Tensors  

In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [ ]:
random_tensor.shape

torch.Size([3, 3])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor_2 = torch.rand(1, 5, 5)
random_tensor_2

tensor([[[0.1702, 0.5485, 0.6515, 0.3809, 0.7065],
         [0.9782, 0.8981, 0.7285, 0.5757, 0.6866],
         [0.9109, 0.7117, 0.1312, 0.0778, 0.5637],
         [0.5784, 0.1405, 0.4521, 0.6681, 0.4298],
         [0.4859, 0.0721, 0.5881, 0.2368, 0.6664]]])

In [ ]:
random_tensor_2.shape

torch.Size([1, 5, 5])

In [ ]:
random_tensor_2.ndim

3

In [ ]:
# Random image tensor
random_img_tensor = torch.rand(size = (224, 224, 3))
random_img_tensor

tensor([[[0.7519, 0.5853, 0.1296],
         [0.1030, 0.5821, 0.2594],
         [0.0398, 0.1056, 0.7281],
         ...,
         [0.0674, 0.5997, 0.8417],
         [0.1290, 0.2778, 0.0262],
         [0.6111, 0.0805, 0.3941]],

        [[0.3250, 0.2249, 0.8956],
         [0.3874, 0.3819, 0.6044],
         [0.9080, 0.6897, 0.1422],
         ...,
         [0.9915, 0.5281, 0.5439],
         [0.8299, 0.5088, 0.4114],
         [0.5413, 0.9679, 0.1973]],

        [[0.0197, 0.1644, 0.3549],
         [0.7142, 0.2620, 0.2996],
         [0.5110, 0.4140, 0.3967],
         ...,
         [0.6158, 0.7133, 0.3955],
         [0.4090, 0.9216, 0.8715],
         [0.0810, 0.3701, 0.4867]],

        ...,

        [[0.4219, 0.3843, 0.0648],
         [0.6848, 0.6604, 0.8532],
         [0.0306, 0.2995, 0.2706],
         ...,
         [0.9575, 0.4182, 0.9426],
         [0.5495, 0.7083, 0.7582],
         [0.7396, 0.7827, 0.6364]],

        [[0.9894, 0.4573, 0.2169],
         [0.8849, 0.1167, 0.6172],
         [0.

In [ ]:
random_img_tensor.shape, random_img_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# ZEROS AND ONES TENSORS

In [ ]:
# zeros tensor
zeros_tensor = torch.zeros(size=(3,3))
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:

# ones tensor
ones_tensor = torch.ones(size=(3,3))
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

# Range Tensor (from one number to another number with a gap)

In [ ]:
# arange
one_to_twenty = torch.arange(start=1, end=21, step=1)
one_to_twenty

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20])

# Tensor DataTypes

In [ ]:
# float32
tensor_float32 = torch.tensor([1.0, 2.0, 3.0],
                              dtype=torch.float32,
                              device=None,
                              requires_grad=False)

In [ ]:
tensor_float32

tensor([1., 2., 3.])

In [ ]:
tensor_float32.dtype

torch.float32

In [ ]:
# converting tensor_float32 into tensor_float16
tensor_float16 = tensor_float32.type(torch.float16)
tensor_float16

tensor([1., 2., 3.], dtype=torch.float16)

In [ ]:
# what happen if we multiply different type of tensor
tensor_float32 * tensor_float16

tensor([1., 4., 9.])

In [ ]:
import torch

# Getting information from tensor
* Datatype - tensor.dtype
* shape - tensor.shape
* device - tensor.device

In [ ]:
# create random tensor
random_tensor = torch.rand(5,5)
print(random_tensor)

tensor([[0.5475, 0.1177, 0.8566, 0.5923, 0.1634],
        [0.6106, 0.7627, 0.1478, 0.8458, 0.3889],
        [0.9120, 0.6615, 0.7772, 0.7004, 0.0841],
        [0.8297, 0.6443, 0.4323, 0.3102, 0.6139],
        [0.6456, 0.2826, 0.1022, 0.3493, 0.0591]])


In [ ]:
print(f"Datatype of random_tensor: {random_tensor.dtype}")
print(f"Shape of a random_tensor: {random_tensor.shape}")
print(f"random_tensor is on device: {random_tensor.device}")

Datatype of random_tensor: torch.float32
Shape of a random_tensor: torch.Size([5, 5])
random_tensor is on device: cpu


# Tensor operation
1. Addition
2. subtraction
3. Multiplication(Element wise)
4. Division
5. Matrix Multiplication

In [ ]:
tensor = torch.tensor([5, 10, 15])
print(tensor)

tensor([ 5, 10, 15])


In [ ]:
# addition
print(tensor + 10)
print(torch.add(tensor, 10))

tensor([15, 20, 25])
tensor([15, 20, 25])


In [ ]:
# subtraction
print(tensor - 10)
print(torch.sub(tensor, 10))

tensor([-5,  0,  5])
tensor([-5,  0,  5])


In [ ]:
# multiplication element-wise
print(f"{tensor} '*' {tensor}")
print(tensor * tensor)
print(torch.mul(tensor, tensor))

tensor([ 5, 10, 15]) '*' tensor([ 5, 10, 15])
tensor([ 25, 100, 225])
tensor([ 25, 100, 225])


In [ ]:
# Division
print(tensor/5)
print(torch.div(tensor, 5))

tensor([1., 2., 3.])
tensor([1., 2., 3.])


# Matrix Multiplication

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 789 µs, sys: 0 ns, total: 789 µs
Wall time: 632 µs


tensor(350)

In [ ]:
# By using loop
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(350)
CPU times: user 2.06 ms, sys: 0 ns, total: 2.06 ms
Wall time: 1.8 ms
